### ISSUE TITLE
IR files not showing up in universal remotes when added

### ISSUE THREAD

**Issue by KPerlman** [MuddledBox/flipperzero-firmware#11]
I have all the directories set up right (infrared/assets/x.ir), but for some reason, the new remotes don't show up anywhere on my flipper. I'm running the latest MuddledBox firmware so I'm not entirely sure what's happening, but any help would be greatly appreciated! Thanks!

**Comment by jiserra** [comment]
I don't think this has nothing to do with MuddleBox firmware. You need to put the infrared `.ir` files under the `infrared` folder and *not* inside the `infrared/assets` folder, otherwise, they won't show up.

**Comment by KPerlman** [comment]
Ohhh, that makes sense. Thanks for the help!
