### ISSUE TITLE
Flipper File System Showing files beginning with ._ 

### ISSUE THREAD

**Issue by BcsHax** [MuddledBox/flipperzero-firmware#7]
**Describe the bug**
Flipper Built in file system is displaying files with "._" when folders are added in a directory. After opening Sub Ghz files file without "._" the actual capture does not send. 

**To Reproduce**
1. Add 1-n folders with multiple files to the Flippers Sub Ghz fold on your SD card
2. From the flipper Desktop press the down arrow to enter the file browser for the
3. Access the folder you added
4. Select a sub ghz file added 
5. Select "Run the app"
6. Select Send

**Expected behavior**

- Flipper file system does not show hidden files with "_"
- Filler allows user to send Sub Ghz transmission as it would if there were no folders

https://user-images.githubusercontent.com/4081137/159097355-bf229d31-12cc-4531-88c6-1faee01122d4.mov

**Comment by MuddledBox** [comment]
Is this just in my FW or on stock FW too?

**Comment by BcsHax** [comment]
No I just realized I had both your Fork open at the same time as the Original flipper one. I shouldn't multi take after working.

---------
Bug opened in wrong location due to USER ERRORRRRRR.
