### ISSUE TITLE
subGhz fails to send packet captured via "Read"

### ISSUE THREAD

**Issue by thejiraguy** [MuddledBox/flipperzero-firmware#8]
**Describe the bug**
I have a ceiling fan that uses a CAME 26bit code at 433.92 to turn on and off the light.  On the official firmware, a packet captured using the subGhz "Read" will work to turn this on and off when replayed under "Save".  On the subGhz unlocked firmware, it will not.  A replay done from "Read Raw" will work in either case. 

**To Reproduce**
1. Navigate to subGhz
2. Select "Read"
3. Capture signal from Remote
4. Save Signal as .sub file
6. Press "Back"
7. Select "Read Raw"
8. Capture signal from remote
9. Save this signal under different name
10. press "back"
11. click "Saved"
12. Select .sub file captured under "Read"
13. Select "Emulate"
14. Send Signal, see failure for light's state to change
15. press back twice
16. Select .sub file captured under "Read Raw"
17. Press "Send," watch light's state change.

**Expected behavior**
CAME packet to be sent over 443.92 using captured CAME packet (Including both READ captured and READ_RAW captured)
[Bedroom_light_subs.zip](https://github.com/MuddledBox/flipperzero-firmware/files/8315474/Bedroom_light_subs.zip)

**Logs**
N/A

**Target**
Specify the target

**Additional context**
Workaround: Use Read_Raw instead of read.

Severity: Low (Workaround Present)

**Comment by MuddledBox** [comment]
It looks like you figured this out, and if there is a bug it is present in both my version and the stock version.
